name: garden_shop
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.2.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  provider: ^6.1.5

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/ # generated files go here
  integrations:
    flutter_svg: true
    lottie: true
